// src/config/calculatorMetadata.js
export const calculatorMetadata = [
  // General
  { screen: 'BMICalculator', name: 'BMI Calculator', category: 'General' },
  { screen: 'BMRCalculator', name: 'BMR Calculator', category: 'General' },
  { screen: 'BodyFatPercentageCalculator', name: 'Body Fat Percentage', category: 'General' },
  { screen: 'CaloricNeedsCalculator', name: 'Caloric Needs', category: 'General' },
  { screen: 'EnergyExpenditureCalculator', name: 'Energy Expenditure', category: 'General' },
  { screen: 'HarrisBenedictCalculator', name: 'Harris-Benedict', category: 'General' },
  { screen: 'IdealBodyWeightCalculator', name: 'Ideal Body Weight', category: 'General' },
  { screen: 'MifflinStJeorCalculator', name: 'Mifflin-St Jeor', category: 'General' },
  { screen: 'WaistCircumferenceCalculator', name: 'Waist Circumference', category: 'General' },
  // Gastroenterology
  { screen: 'AlvaradoScore', name: 'Alvarado Score', category: 'Gastroenterology' },
  { screen: 'BISAPCalculator', name: 'BISAP Score', category: 'Gastroenterology' },
  { screen: 'BarrettsEsophagusRisk', name: "Barrett's Esophagus Risk", category: 'Gastroenterology' },
  { screen: 'BowelCancerScreening', name: 'Bowel Cancer Screening', category: 'Gastroenterology' },
  { screen: 'BristolStoolChart', name: 'Bristol Stool Chart', category: 'Gastroenterology' },
  { screen: 'ChildPughScore', name: 'Child-Pugh Score', category: 'Gastroenterology' },
  { screen: 'CrohnsDiseaseActivity', name: "Crohn's Disease Activity", category: 'Gastroenterology' },
  { screen: 'FIB4Calculator', name: 'FIB-4 Score', category: 'Gastroenterology' },
  { screen: 'GERDQualityOfLife', name: 'GERD Quality of Life', category: 'Gastroenterology' },
  { screen: 'GERDSeverityScore', name: 'GERD Severity Score', category: 'Gastroenterology' },
  { screen: 'GIBleedingRisk', name: 'GI Bleeding Risk', category: 'Gastroenterology' },
  // ICU
  { screen: 'APACHE', name: 'APACHE Score', category: 'ICU' },
  { screen: 'QSOFAScoreCalculator', name: 'qSOFA Score', category: 'ICU' },
  { screen: 'SOFACalculator', name: 'SOFA Score', category: 'ICU' },
  // Nephrology
  { screen: 'CKDEpiCalculator', name: 'CKD-EPI Calculator', category: 'Nephrology' },
  { screen: 'ChronicKidneyDiseaseStageCalculator', name: 'CKD Stage', category: 'Nephrology' },
  { screen: 'CreatinineClearanceCalculator', name: 'Creatinine Clearance', category: 'Nephrology' },
  { screen: 'ElectrolyteImbalanceCalculator', name: 'Electrolyte Imbalance', category: 'Nephrology' },
  { screen: 'GFRCalculator', name: 'GFR Calculator', category: 'Nephrology' },
  { screen: 'HypertensiveNephropathyRiskScore', name: 'Hypertensive Nephropathy Risk', category: 'Nephrology' },
  { screen: 'KidneyStoneRiskAssessment', name: 'Kidney Stone Risk', category: 'Nephrology' },
  { screen: 'NephroticSyndromeScore', name: 'Nephrotic Syndrome Score', category: 'Nephrology' },
  { screen: 'UricAcidCalculator', name: 'Uric Acid Calculator', category: 'Nephrology' },
  { screen: 'UrineProteinToCreatinineRatio', name: 'Urine Protein to Creatinine Ratio', category: 'Nephrology' },
  // Neurology
  { screen: 'ABCD2Score', name: 'ABCD2 Score', category: 'Neurology' },
  { screen: 'AHASAScore', name: 'AHASA Score', category: 'Neurology' },
  { screen: 'ApacheII', name: 'Apache II Score', category: 'Neurology' },
  { screen: 'CHADSVASc', name: 'CHA2DS2-VASc Score', category: 'Neurology' },
  { screen: 'CheckBox', name: 'CheckBox', category: 'Neurology' },
  { screen: 'DenverII', name: 'Denver II', category: 'Neurology' },
  { screen: 'EDSS', name: 'EDSS Score', category: 'Neurology' },
  { screen: 'EQ5D', name: 'EQ-5D Score', category: 'Neurology' },
  { screen: 'EpilepsyRisk', name: 'Epilepsy Risk', category: 'Neurology' },
  { screen: 'GAD7', name: 'GAD-7 Score', category: 'Neurology' },
  { screen: 'GCS', name: 'Glasgow Coma Scale', category: 'Neurology' },
  // Obstetrics
  { screen: 'APGARScore', name: 'APGAR Score', category: 'Obstetrics' },
  { screen: 'AmnioticFluidIndex', name: 'Amniotic Fluid Index', category: 'Obstetrics' },
  { screen: 'BishopScore', name: 'Bishop Score', category: 'Obstetrics' },
  { screen: 'EstimatedDueDate', name: 'Estimated Due Date', category: 'Obstetrics' },
  { screen: 'EstimatedFetalWeight', name: 'Estimated Fetal Weight', category: 'Obstetrics' },
  { screen: 'GDMScreening', name: 'GDM Screening', category: 'Obstetrics' },
  { screen: 'GestationalAgeCalculator', name: 'Gestational Age', category: 'Obstetrics' },
  { screen: 'HELLPSyndromeRisk', name: 'HELLP Syndrome Risk', category: 'Obstetrics' },
  { screen: 'PreeclampsiaRisk', name: 'Preeclampsia Risk', category: 'Obstetrics' },
  { screen: 'VBACRiskCalculator', name: 'VBAC Risk Calculator', category: 'Obstetrics' },
  // Pulmonary
  { screen: 'ACTCalculator', name: 'ACT Calculator', category: 'Pulmonary' },
  { screen: 'BODECalculator', name: 'BODE Index', category: 'Pulmonary' },
  { screen: 'CATCalculator', name: 'CAT Calculator', category: 'Pulmonary' },
  { screen: 'CURB65', name: 'CURB-65 Score', category: 'Pulmonary' },
  { screen: 'CalculatorForm', name: 'Calculator Form', category: 'Pulmonary' },
  { screen: 'FEV1FVCCalculator', name: 'FEV1/FVC Calculator', category: 'Pulmonary' },
  { screen: 'LungAgeCalculator', name: 'Lung Age Calculator', category: 'Pulmonary' },
  { screen: 'MMRCCalculator', name: 'mMRC Calculator', category: 'Pulmonary' },
  { screen: 'PEFRCalculator', name: 'PEFR Calculator', category: 'Pulmonary' },
  { screen: 'PERCCalculator', name: 'PERC Calculator', category: 'Pulmonary' },
  { screen: 'PSICalculator', name: 'PSI Calculator', category: 'Pulmonary' },
  // Orthopedics
  { screen: 'ConstantMurleyScore', name: 'Constant-Murley Score', category: 'Orthopedics' },
  { screen: 'FRAC', name: 'FRAC Score', category: 'Orthopedics' },
  { screen: 'HarrisHipScore', name: 'Harris Hip Score', category: 'Orthopedics' },
  { screen: 'JointReplacementRiskCalculator', name: 'Joint Replacement Risk', category: 'Orthopedics' },
  { screen: 'OsteoporosisRiskCalculator', name: 'Osteoporosis Risk', category: 'Orthopedics' },
  { screen: 'OswestryDisabilityIndex', name: 'Oswestry Disability Index', category: 'Orthopedics' },
  { screen: 'WOMACCalculator', name: 'WOMAC Calculator', category: 'Orthopedics' },
  // Cardiovascular
  { screen: 'ASCVD', name: 'ASCVD Risk', category: 'Cardiovascular' },
  { screen: 'CHA2DS2VASc', name: 'CHA2DS2-VASc Score', category: 'Cardiovascular' },
  { screen: 'Framingham', name: 'Framingham Risk', category: 'Cardiovascular' },
  { screen: 'GRACE', name: 'GRACE Score', category: 'Cardiovascular' },
  { screen: 'HASBLED', name: 'HAS-BLED Score', category: 'Cardiovascular' },
  { screen: 'TIMI', name: 'TIMI Score', category: 'Cardiovascular' },
];